services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_pfe
      MYSQL_DATABASE: my_nestjs_project
      MYSQL_USER: zied
      MYSQL_PASSWORD: azertyS20645307
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./test1
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: zied
      DB_PASSWORD: azertyS20645307
      DB_NAME: my_nestjs_project
      JWT_SECRET: "123456"
    depends_on:
      - db

  frontend:
    build:
      context: ./ERP
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
